<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.Master" AutoEventWireup="true" CodeBehind="editTicket.aspx.cs" Inherits="Lab2.editTicket" EnableEventValidation="false" %>

<%--Kirsi And Josh Coleman 2/15/21--%>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

    <div class="row justify-content-around">
        <div class=" col-5">
            <div class="card" id="serviceCard">
                <div class="card-header">
                </div>

                <div class="card-body">
                    <asp:DetailsView
                        ID="dvServiceDetails"
                        DataKeyNames="serviceID"
                        DataSourceID="srcServiceData"
                        AutoGenerateEditButton="true"
                        AutoGenerateRows="false"
                        DefaultMode="ReadOnly"
                        class="table table-bordered table-condensed"
                        runat="server">
                        <Fields>
                            <asp:TemplateField HeaderText="Service Type">
                                <ItemTemplate>
                                    <asp:Label ID="lblService" runat="server" Text='<%#Eval("serviceType").ToString() == "M" ? "Move" : "Auction"%>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>

                            <asp:BoundField DataField="serviceOpenDate" HeaderText="Open Date" />

                            <asp:TemplateField HeaderText="Status">
                                <ItemTemplate>
                                    <asp:Label ID="lblStatus" runat="server" Text='<%#(Eval("serviceStatus").ToString()) == "True" ? "Active" : "Inactive"%>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:BoundField DataField="serviceDeadlineStart" HeaderText="Deadline Start" />
                            <asp:BoundField DataField="serviceDeadlineEnd" HeaderText="Deadline End" />
                            <asp:TemplateField HeaderText="Last Updated" ControlStyle-Font-Italic="true">
                                <ItemTemplate>
                                    <asp:Label ID="lblLastUpdated" runat="server" Font-Italic="true"
                                        Text='<%# Bind("lastUpdated") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                        </Fields>
                    </asp:DetailsView>

                    <asp:SqlDataSource
                        ID="srcServiceData"
                        ConnectionString="<%$ ConnectionStrings:Connect %>"
                        SelectCommand="SELECT * from Service WHERE SERVICE.serviceID = @serviceID"
                        runat="server">
                        <SelectParameters>
                            <asp:SessionParameter Name="serviceID" SessionField="selectedService" />
                        </SelectParameters>
                    </asp:SqlDataSource>

                    <asp:GridView
                        ID="gvServiceAddresses"
                        AutoGenerateColumns="false"
                        AutoGenerateEditButton="true"
                        AutoGenerateDeleteButton="true"
                        AutoGenerateInsertButton="true"
                        runat="server"
                        DataKeyNames="addressID"
                        DataSourceID="srcServiceAddresses"
                        class="table table-bordered table-condensed">
                        <Columns>
                            <asp:TemplateField>
                                <ItemTemplate>
                                    <asp:Label ID="addressType" runat="server" Text='<%# (Eval("addressType").ToString() == "P") ? "Pick Up Location" : "Drop Off" %>'></asp:Label>
                                </ItemTemplate>
                                <EditItemTemplate>
                                    <asp:DropDownList ID="ddlAddressType" runat="server">
                                        <asp:ListItem Text="Pick Up" Value="P"></asp:ListItem>
                                        <asp:ListItem Text="Drop Off" Value="D"></asp:ListItem>
                                    </asp:DropDownList>
                                </EditItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Address">
                                <EditItemTemplate>
                                    <div class="form-group">
                                        <asp:TextBox ID="txtAddress" runat="server" Text='<%# Bind("streetAddress") %>' class="form-control"></asp:TextBox>
                                        <asp:RequiredFieldValidator ID="rfvAddress" runat="server"
                                            ErrorMessage="RequiredFieldValidator" ControlToValidate="txtAddress"
                                            Text="Please Enter An Address.">
                                        </asp:RequiredFieldValidator>
                                    </div>

                                    <div class="row form-group">
                                        <div class="col-md-6">
                                            <asp:TextBox ID="txtCity" runat="server" Text='<%# Bind("city") %>' class="form-control"></asp:TextBox>
                                            <asp:RequiredFieldValidator ID="rfvCity" runat="server"
                                                ErrorMessage="RequiredFieldValidator" ControlToValidate="txtCity"
                                                Text="Please Enter A City.">
                                            </asp:RequiredFieldValidator>
                                        </div>

                                        <div class="col-md-2">
                                            <asp:DropDownList ID="ddlState" runat="server" class="form-control" SelectedValue='<%# Bind("state") %>'>
                                                <asp:ListItem Value="AL">Alabama</asp:ListItem>
                                                <asp:ListItem Value="AK">Alaska</asp:ListItem>
                                                <asp:ListItem Value="AZ">Arizona</asp:ListItem>
                                                <asp:ListItem Value="AR">Arkansas</asp:ListItem>
                                                <asp:ListItem Value="CA">California</asp:ListItem>
                                                <asp:ListItem Value="CO">Colorado</asp:ListItem>
                                                <asp:ListItem Value="CT">Connecticut</asp:ListItem>
                                                <asp:ListItem Value="DC">District of Columbia</asp:ListItem>
                                                <asp:ListItem Value="DE">Delaware</asp:ListItem>
                                                <asp:ListItem Value="FL">Florida</asp:ListItem>
                                                <asp:ListItem Value="GA">Georgia</asp:ListItem>
                                                <asp:ListItem Value="HI">Hawaii</asp:ListItem>
                                                <asp:ListItem Value="ID">Idaho</asp:ListItem>
                                                <asp:ListItem Value="IL">Illinois</asp:ListItem>
                                                <asp:ListItem Value="IN">Indiana</asp:ListItem>
                                                <asp:ListItem Value="IA">Iowa</asp:ListItem>
                                                <asp:ListItem Value="KS">Kansas</asp:ListItem>
                                                <asp:ListItem Value="KY">Kentucky</asp:ListItem>
                                                <asp:ListItem Value="LA">Louisiana</asp:ListItem>
                                                <asp:ListItem Value="ME">Maine</asp:ListItem>
                                                <asp:ListItem Value="MD">Maryland</asp:ListItem>
                                                <asp:ListItem Value="MA">Massachusetts</asp:ListItem>
                                                <asp:ListItem Value="MI">Michigan</asp:ListItem>
                                                <asp:ListItem Value="MN">Minnesota</asp:ListItem>
                                                <asp:ListItem Value="MS">Mississippi</asp:ListItem>
                                                <asp:ListItem Value="MO">Missouri</asp:ListItem>
                                                <asp:ListItem Value="MT">Montana</asp:ListItem>
                                                <asp:ListItem Value="NE">Nebraska</asp:ListItem>
                                                <asp:ListItem Value="NV">Nevada</asp:ListItem>
                                                <asp:ListItem Value="NH">New Hampshire</asp:ListItem>
                                                <asp:ListItem Value="NJ">New Jersey</asp:ListItem>
                                                <asp:ListItem Value="NM">New Mexico</asp:ListItem>
                                                <asp:ListItem Value="NY">New York</asp:ListItem>
                                                <asp:ListItem Value="NC">North Carolina</asp:ListItem>
                                                <asp:ListItem Value="ND">North Dakota</asp:ListItem>
                                                <asp:ListItem Value="OH">Ohio</asp:ListItem>
                                                <asp:ListItem Value="OK">Oklahoma</asp:ListItem>
                                                <asp:ListItem Value="OR">Oregon</asp:ListItem>
                                                <asp:ListItem Value="PA">Pennsylvania</asp:ListItem>
                                                <asp:ListItem Value="RI">Rhode Island</asp:ListItem>
                                                <asp:ListItem Value="SC">South Carolina</asp:ListItem>
                                                <asp:ListItem Value="SD">South Dakota</asp:ListItem>
                                                <asp:ListItem Value="TN">Tennessee</asp:ListItem>
                                                <asp:ListItem Value="TX">Texas</asp:ListItem>
                                                <asp:ListItem Value="UT">Utah</asp:ListItem>
                                                <asp:ListItem Value="VT">Vermont</asp:ListItem>
                                                <asp:ListItem Value="VA">Virginia</asp:ListItem>
                                                <asp:ListItem Value="WA">Washington</asp:ListItem>
                                                <asp:ListItem Value="WV">West Virginia</asp:ListItem>
                                                <asp:ListItem Value="WI">Wisconsin</asp:ListItem>
                                                <asp:ListItem Value="WY">Wyoming</asp:ListItem>
                                            </asp:DropDownList>
                                            <asp:RequiredFieldValidator ID="rfvState" runat="server"
                                                ErrorMessage="RequiredFieldValidator" ControlToValidate="ddlState"
                                                Text="Please Select A State.">
                                            </asp:RequiredFieldValidator>
                                        </div>

                                        <div class="col-md-4">
                                            <asp:TextBox ID="txtZipCode" runat="server" Text='<%# Bind("zipcode") %>' class="form-control"></asp:TextBox>
                                            <asp:RequiredFieldValidator ID="rfvZipCode" runat="server"
                                                ErrorMessage="RequiredFieldValidator" ControlToValidate="txtZipCode"
                                                Text="Please Enter Zip Code.">
                                            </asp:RequiredFieldValidator>
                                        </div>
                                    </div>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="lblAddress" runat="server" Text='<%# Bind("streetAddress") %>'></asp:Label>
                                    <asp:Label ID="lblCity" runat="server" Text='<%# Bind("city") %>'></asp:Label>
                                    <asp:Label ID="lblState" runat="server" Text='<%# Bind("state") %>'></asp:Label>
                                    <asp:Label ID="lblZip" runat="server" Text='<%# Bind("zipcode") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                        </Columns>
                    </asp:GridView>
                    <div class="table table-bordered table-condensed">
                        <div class="d-table-row">
                            <div class="d-table-cell">
                                <asp:Button ID="btnNewAddress" OnClick="btnNewAddress_Click" runat="server" Text="New Address" Class="btn btn-outline-secondary" />
                                </div>
                            <div class="d-table-cell">
                                <asp:DropDownList ID="ddlAddressType" runat="server">
                                        <asp:ListItem Text="Pick Up" Value="P"></asp:ListItem>
                                        <asp:ListItem Text="Drop Off" Value="D"></asp:ListItem>
                                    </asp:DropDownList>
                                </div>
                            <div class="d-table-cell">
                                <div class="form-group">
                                        <asp:TextBox ID="txtAddress" runat="server" Placeholder="Address" class="form-control"></asp:TextBox>
                                        <asp:RequiredFieldValidator ID="rfvAddress" runat="server"
                                            ErrorMessage="RequiredFieldValidator" ControlToValidate="txtAddress"
                                            Text="Please Enter An Address.">
                                        </asp:RequiredFieldValidator>
                                    </div>

                                    <div class="row form-group">
                                        <div class="col-md-6">
                                            <asp:TextBox ID="txtCity" runat="server" Placeholder="City" class="form-control"></asp:TextBox>
                                            <asp:RequiredFieldValidator ID="rfvCity" runat="server"
                                                ErrorMessage="RequiredFieldValidator" ControlToValidate="txtCity"
                                                Text="Please Enter A City.">
                                            </asp:RequiredFieldValidator>
                                        </div>

                                        <div class="col-md-2">
                                            <asp:DropDownList ID="ddlState" runat="server" class="form-control" SelectedValue='<%# Bind("state") %>'>
                                                <asp:ListItem Value="AL">Alabama</asp:ListItem>
                                                <asp:ListItem Value="AK">Alaska</asp:ListItem>
                                                <asp:ListItem Value="AZ">Arizona</asp:ListItem>
                                                <asp:ListItem Value="AR">Arkansas</asp:ListItem>
                                                <asp:ListItem Value="CA">California</asp:ListItem>
                                                <asp:ListItem Value="CO">Colorado</asp:ListItem>
                                                <asp:ListItem Value="CT">Connecticut</asp:ListItem>
                                                <asp:ListItem Value="DC">District of Columbia</asp:ListItem>
                                                <asp:ListItem Value="DE">Delaware</asp:ListItem>
                                                <asp:ListItem Value="FL">Florida</asp:ListItem>
                                                <asp:ListItem Value="GA">Georgia</asp:ListItem>
                                                <asp:ListItem Value="HI">Hawaii</asp:ListItem>
                                                <asp:ListItem Value="ID">Idaho</asp:ListItem>
                                                <asp:ListItem Value="IL">Illinois</asp:ListItem>
                                                <asp:ListItem Value="IN">Indiana</asp:ListItem>
                                                <asp:ListItem Value="IA">Iowa</asp:ListItem>
                                                <asp:ListItem Value="KS">Kansas</asp:ListItem>
                                                <asp:ListItem Value="KY">Kentucky</asp:ListItem>
                                                <asp:ListItem Value="LA">Louisiana</asp:ListItem>
                                                <asp:ListItem Value="ME">Maine</asp:ListItem>
                                                <asp:ListItem Value="MD">Maryland</asp:ListItem>
                                                <asp:ListItem Value="MA">Massachusetts</asp:ListItem>
                                                <asp:ListItem Value="MI">Michigan</asp:ListItem>
                                                <asp:ListItem Value="MN">Minnesota</asp:ListItem>
                                                <asp:ListItem Value="MS">Mississippi</asp:ListItem>
                                                <asp:ListItem Value="MO">Missouri</asp:ListItem>
                                                <asp:ListItem Value="MT">Montana</asp:ListItem>
                                                <asp:ListItem Value="NE">Nebraska</asp:ListItem>
                                                <asp:ListItem Value="NV">Nevada</asp:ListItem>
                                                <asp:ListItem Value="NH">New Hampshire</asp:ListItem>
                                                <asp:ListItem Value="NJ">New Jersey</asp:ListItem>
                                                <asp:ListItem Value="NM">New Mexico</asp:ListItem>
                                                <asp:ListItem Value="NY">New York</asp:ListItem>
                                                <asp:ListItem Value="NC">North Carolina</asp:ListItem>
                                                <asp:ListItem Value="ND">North Dakota</asp:ListItem>
                                                <asp:ListItem Value="OH">Ohio</asp:ListItem>
                                                <asp:ListItem Value="OK">Oklahoma</asp:ListItem>
                                                <asp:ListItem Value="OR">Oregon</asp:ListItem>
                                                <asp:ListItem Value="PA">Pennsylvania</asp:ListItem>
                                                <asp:ListItem Value="RI">Rhode Island</asp:ListItem>
                                                <asp:ListItem Value="SC">South Carolina</asp:ListItem>
                                                <asp:ListItem Value="SD">South Dakota</asp:ListItem>
                                                <asp:ListItem Value="TN">Tennessee</asp:ListItem>
                                                <asp:ListItem Value="TX">Texas</asp:ListItem>
                                                <asp:ListItem Value="UT">Utah</asp:ListItem>
                                                <asp:ListItem Value="VT">Vermont</asp:ListItem>
                                                <asp:ListItem Value="VA">Virginia</asp:ListItem>
                                                <asp:ListItem Value="WA">Washington</asp:ListItem>
                                                <asp:ListItem Value="WV">West Virginia</asp:ListItem>
                                                <asp:ListItem Value="WI">Wisconsin</asp:ListItem>
                                                <asp:ListItem Value="WY">Wyoming</asp:ListItem>
                                            </asp:DropDownList>
                                            <asp:RequiredFieldValidator ID="rfvState" runat="server"
                                                ErrorMessage="RequiredFieldValidator" ControlToValidate="ddlState"
                                                Text="Please Select A State.">
                                            </asp:RequiredFieldValidator>
                                        </div>

                                        <div class="col-md-4">
                                            <asp:TextBox ID="txtZipCode" runat="server" PlaceHolder="Zip" class="form-control"></asp:TextBox>
                                            <asp:RequiredFieldValidator ID="rfvZipCode" runat="server"
                                                ErrorMessage="RequiredFieldValidator" ControlToValidate="txtZipCode"
                                                Text="Please Enter Zip Code.">
                                            </asp:RequiredFieldValidator>
                                        </div>
                                    </div>
                            </div>    
                        </div>
                    </div>

                    <asp:SqlDataSource
                        ID="srcServiceAddresses"
                        ConnectionString="<%$ ConnectionStrings:Connect %>"
                        SelectCommand="SELECT ADDRESSES.addressID, ADDRESSES.streetAddress, ADDRESSES.city, ADDRESSES.state, ADDRESSES.zipcode, ADDRESSES.addressType, ADDRESSES.serviceID
                                    FROM ADDRESSES WHERE ADDRESSES.serviceID = @serviceID"
                        UpdateCommand="UPDATE ADDRESSES SET streetAddress=@streetAddress, city=@city, state=@state, zipcode=@zipcode where addressID=@addressID"
                        InsertCommand="INSERT into ADDRESSES(streetAddress, city, state, zipcode, addressType, serviceID) VALUES(@streetAddress, @city, @state, @zipcode,@addressType,@serviceID)"
                        DeleteCommand="Delete from Addresses WHERE addressID = @addressID"
                        runat="server">
                        <SelectParameters>
                            <asp:SessionParameter Name="serviceID" SessionField="selectedService" />
                        </SelectParameters>
                        <InsertParameters>
                            <asp:ControlParameter Name="streetAddress" ControlID="txtAddress" Type="String" />
                            <asp:ControlParameter Name="city" ControlID="txtCity" Type="String" />
                            <asp:ControlParameter Name="state" ControlID="ddlState" Type="String" />
                            <asp:ControlParameter Name="zipcode" ControlID="txtZipCode" />
                            <asp:ControlParameter Name="addressType" ControlID="ddlAddressType" Type="String" />
                            <asp:SessionParameter Name="serviceID" SessionField="selectedService" />
                        </InsertParameters>
                    </asp:SqlDataSource>
                </div>

            </div>
        </div>

        <div class="col-5">
            <div class="card mb-2">
                <div class="card-header">
                    <ul class="nav nav-tabs card-header-tabs pull-right" id="myTab" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active" id="notes-tab" data-toggle="tab" href="#note" role="tab" aria-controls="Notes" aria-selected="true">Notes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="newNote-tab" data-toggle="tab" href="#newNote" role="tab" aria-controls="newNotes" aria-selected="false">New Note</a>
                        </li>
                    </ul>
                </div>
                <div class="card-body">
                    <div class="tab-content" id="myTabContent">
                        <div class="tab-pane fade show active" id="note" role="tabpanel" aria-labelledby="notes-tab">
                            <asp:GridView
                                ID="gvNotes"
                                DataSourceID="srcNotes"
                                AutoGenerateColumns="false"
                                DataKeyNames="ticketID"
                                OnRowDataBound="gvNotes_RowDataBound"
                                OnSelectedIndexChanged="gvNotes_SelectedIndexChanged"
                                runat="server"
                                class="table table-bordered table-condensed table-hover">
                                <Columns>
                                    <asp:BoundField DataField="CreationDate" HeaderText="Creation Date" />
                                    <asp:BoundField DataField="CreatedBy" HeaderText="Created By" />
                                    <asp:BoundField DataField="NoteTitle" HeaderText="Note Title" />
                                </Columns>
                            </asp:GridView>

                            <asp:SqlDataSource
                                ID="srcNotes"
                                ConnectionString="<%$ ConnectionStrings:Connect %>"
                                SelectCommand="SELECT TicketNote.ticketID, TICKETNOTE.creationDate as 'CreationDate', EMPLOYEE.firstName + ' ' + EMPLOYEE.lastName as 'CreatedBy', TICKETNOTE.noteTitle as 'NoteTitle' 
                            FROM TICKETNOTE INNER JOIN EMPLOYEE on TICKETNOTE.noteCreator = EMPLOYEE.employeeID WHERE TICKETNOTE.serviceID = @serviceID order by TICKETNOTE.creationDate desc"
                                runat="server">
                                <SelectParameters>
                                    <asp:SessionParameter Name="serviceID" SessionField="selectedService" />
                                </SelectParameters>
                            </asp:SqlDataSource>
                            <asp:Button ID="btnNewNote" runat="server" Text="Add Note" OnClick="btnNewNote_Click" Class="btn btn-outline-secondary" />
                        </div>

                        <div class="tab-pane fade" id="newNote" role="tabpanel" aria-labelledby="newNote-tab">
                            <div class=" form-group">
                                <asp:TextBox ID="txtNoteTitle" runat="server" Placeholder="Note Title" class="form-control"></asp:TextBox>
                                <asp:RequiredFieldValidator ID="rfvNoteTitle" runat="server" ErrorMessage="RequiredFieldValidator" ValidationGroup="newNote" ControlToValidate="txtNoteTitle" Text="Please create a title."></asp:RequiredFieldValidator>

                                <asp:TextBox ID="txtNoteBody" runat="server" TextMode="MultiLine" Placeholder="Note Body" class="form-control"></asp:TextBox>
                                <asp:RequiredFieldValidator ID="rfvNoteBody" runat="server" ErrorMessage="RequiredFieldValidator" ValidationGroup="newNote" ControlToValidate="txtNoteBody" Text="Please enter note body."></asp:RequiredFieldValidator>
                            </div>

                            <div class="form-group">
                                <asp:Button ID="btnCreateNote" runat="server" Text="Create" OnClick="btnCreateNote_Click" ValidationGroup="newNote" class="btn btn-outline-secondary" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-header">
                    <asp:Label ID="lblWorkflow" Text="Service Workers" runat="server" Font-Bold="true"></asp:Label>
                </div>
                <div class="card-body">
                    <asp:GridView
                        ID="gvAssignmnets"
                        DataSourceID="srcAssignments"
                        runat="server"
                        class="table table-bordered table-condensed">
                    </asp:GridView>

                    <asp:SqlDataSource
                        ID="srcAssignments"
                        ConnectionString="<%$ ConnectionStrings:Connect %>"
                        SelectCommand="SELECT EMPLOYEE.firstName as 'First Name', EMPLOYEE.lastName as 'Last Name', ASSIGNMENT.startDate 'Start Date', ASSIGNMENT.employeeRole as 'Role' FROM ASSIGNMENT INNER JOIN
                  EMPLOYEE ON ASSIGNMENT.employeeID = EMPLOYEE.employeeID WHERE ASSIGNMENT.serviceID = @serviceID"
                        runat="server">
                        <SelectParameters>
                            <asp:SessionParameter Name="serviceID" SessionField="selectedService" />
                        </SelectParameters>
                    </asp:SqlDataSource>
                </div>
            </div>
        </div>
    </div>
</asp:Content>
